services:
  app:
    volumes:
      - ./app:/var/www/html/app
      - ./bootstrap/app.php:/var/www/html/bootstrap/app.php
      - ./config:/var/www/html/config
      - ./database:/var/www/html/database
      - ./resources:/var/www/html/resources
      - ./routes:/var/www/html/routes

  web:
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
